OrderingSystem/Customer/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from Customer import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='homepage'),
    #url(r'^restaurant$', views.RestaurantView.as_view(), name='restaurantPage'),
    url(r'^(?P<pk>[0-9]+)/order$', login_required(views.OrderView.as_view()), name='orderPage'),
    url(r'^(?P<pk>[0-9]+)/complete$', login_required(views.CompleteOrderView.as_view()), name='completeOrder'),
    url(r'^restaurant/(?P<pk>[0-9]+)/$', views.RestaurantAPIView.as_view(), name='resaurant_detail_api'),
    url(r'^(?P<pk>[0-9]+)/$', views.RestaurantDetailView.as_view(), name='resaurant_detail'),
    url(r'^(?P<pk>[0-9]+)/dishlist$', views.DishListView.as_view(), name='resaurant_dishlist'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/$', views.DetailDish.as_view(), name='resaurant_detaildish'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/like$', views.DetailDishLike.as_view(), name='resaurant_detaildish_like'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/unliked$', views.DetailDishUnlike.as_view(), name='resaurant_detaildish_unlike'),
    url(r'^filter$', views.FilterView.as_view(), name='resaurant_filter'),
    url(r'^cookie/$',views.CookieView.as_view(),name="order_cookie"),
    url(r'^searchresult/$',views.search.as_view(),name="searchpage"),
    )

#urlpatterns = format_suffix_patterns(urlpatterns)

OrderingSystem/OrderingSystem/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.forms import RegistrationForm
from registration.backends.default.views import RegistrationView

urlpatterns = patterns(
    '',
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationForm), name='registration_register'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^business/', include('business.urls', namespace='business')),
    url(r'^', include('Customer.urls', namespace='Customer')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OrderingSystem/business/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse

from geopy.geocoders.googlev3 import GoogleV3
from geopy.exc import GeocoderQueryError
from urllib2 import URLError

from OrderingSystem import settings


class Restaurant(models.Model):
    baseUser = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField('Restaurant Name', max_length=50)
    # category = models.CharField('Food Type', max_length=50, blank=True)
    msg = models.TextField('Description', blank=True, null=True)
    image = models.FileField(upload_to='restaurant/%Y/%m/%d', null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^[+|\d][0-9() -]*\d$', message="Please enter a correct phone number.")
    phone = models.CharField('Business Phone', validators=[phone_regex], null=True, blank=True, max_length=20)
    Provide_Delivery = models.BooleanField(default=False)
    Children_Friendly = models.BooleanField(default=False)
    Wifi = models.BooleanField(default=False)
    Vegan = models.BooleanField(default=False)
    Gluten_Free = models.BooleanField(default=False)

    # time reference
    createdAt = models.DateTimeField(auto_now_add=1, auto_now=0)
    lastAccessAt = models.DateTimeField(auto_now=1, auto_now_add=0)
    food_choices = (
        ('ff', 'FastFood'),
        ('cns', 'Chinese'),
        ('jpf', 'Japanese'),
        ('wst', 'Western'),
    )
    category = models.CharField('Food Type', max_length=10, choices=food_choices, default='cns')

    time_choices = (
        ('06:00', '06:00'),
        ('07:00', '07:00'),
        ('08:00', '08:00'),
        ('09:00', '09:00'),
        ('10:00', '10:00'),
        ('11:00', '11:00'),
        ('12:00', '12:00'),
        ('13:00', '13:00'),
        ('14:00', '14:00'),
        ('15:00', '15:00'),
        ('16:00', '16:00'),
        ('17:00', '17:00'),
        ('18:00', '18:00'),
        ('19:00', '19:00'),
        ('20:00', '20:00'),
        ('21:00', '21:00'),
        ('22:00', '22:00'),
        ('23:00', '23:00'),
        ('24:00', '24:00'),
        ('01:00', '01:00'),
        ('02:00', '02:00'),
        ('03:00', '03:00'),
        ('04:00', '04:00'),
        ('05:00', '05:00'),
    )
    opentime = models.CharField('Open Time', max_length=10, choices=time_choices, default='08:00')
    closetime = models.CharField('Close Time', max_length=10, choices=time_choices, default='22:00')

    def get_absolute_url(self):
        return reverse('business:RestaurantPage')


class Address(models.Model):
    restaurant = models.ForeignKey(Restaurant, related_name="address")
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=20)
    zipcode = models.CharField(max_length=10)
    # gis = gis_models.GeoManager()

    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    # location = gis_models.PointField(u"longitude/latitude", geography=True, blank=True, null=True)

    def __unicode__(self):
        return str(self.latitude) + " " + str(self.longitude)

    def save(self, **kwargs):
        address = u'%s %s, %s %s' % (self.address, self.city, self.state, self.zipcode)
        address = address.encode('utf-8')
        try:
            response = GoogleV3().geocode(address)

        except (URLError, GeocoderQueryError, ValueError):
            pass
        else:
            if response:
                _, coordinates = response
                self.latitude = coordinates[0]
                self.longitude = coordinates[1]
            else:
                self.latitude = None
                self.longitude = None
                # point = "POINT(%s %s)" % (coordinates[1], coordinates[0])
                # self.location = geos.fromstr(point)

        super(Address, self).save()


class Dish(models.Model):
    restaurant = models.ForeignKey(Restaurant)
    name = models.CharField(max_length=50)
    price = models.FloatField()
    image = models.FileField(upload_to='dishes/%Y/%m/%d', blank=True, null=True)
    liked = models.IntegerField(default=0)
    unliked = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)

    type_choices = (
        ('ent', 'Entries'),
        ('mai', 'Main'),
        ('des', 'Dessert'),
        ('drk', 'Drinks'),
    )
    dishcategory = models.CharField('Dish Type', max_length=10, choices=type_choices, default='ent')


class RestaurantComment(models.Model):
    comment = models.TextField()
    restaurant = models.ForeignKey(Restaurant)


class DishComment(models.Model):
    comment = models.TextField()
    dish = models.ForeignKey(Dish)

OrderingSystem/Customer/forms.py
__author__ = 'lockliu'
__author__ = 'jasonZhao'

from django import forms
from django.forms import NumberInput
from models import Order, Comment_R


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['restaurant']


class OrderDetailForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['restaurant', 'buyer', 'delivery_type', 'paid', 'location','time', 'total_price', 'discount']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment_R
        exclude = ['buyer', 'restaurant', 'time']
        # widgets = {
        #    'rating': NumberInput(attrs={'class' :'ratingInput'}),
        # }


class NavSearchForm(forms.Form):
  query = forms.CharField(label="",max_length=30, required=False)
  exclude=[query.label]

OrderingSystem/Customer/views.py
import datetime
import json

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.core.urlresolvers import reverse
from business.models import Restaurant, Address, Dish, DishComment
from accounts.models import CustomUser

from models import Order, OrderItem, Comment_R
from forms import OrderForm, OrderDetailForm, CommentForm, NavSearchForm
from serializers import DishSerializer,DishCommentSerializer, RestaurantSerializer
# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from django.core import serializers
from OrderingSystem import settings
from django.utils.encoding import smart_str
from haystack.query import SearchQuerySet
from business.models import Restaurant

class IndexView(TemplateView):
    template = 'Customer/homepage.html'

    def get(self, request, *args, **kwargs):
        restaurant_list = Restaurant.objects.all()
        address_list = Address.objects.all()
        comment_list = Comment_R.objects.all()

        restaurant_address_rating_list = []
        for r in restaurant_list:
            oneList = {}
            oneList['r'] = r
            oneList['address'] = Address.objects.filter(restaurant = r)
            ratingList = Comment_R.objects.filter(restaurant = r)

            total = 0
            if ratingList is not None:
                for r in ratingList:
                    total = r.rating + total
            
            if len(ratingList) == 0:
                rate = 0
            else:
                rate = total / len(ratingList)

            
            rate = round(rate, 1)
            oneList["rating"] = rate
            oneList["vote"] = len(ratingList)
            restaurant_address_rating_list.append(oneList)

        # return HttpResponse(restaurant_address_rating_list[0]['addressList'][0].address)
        return render(request, self.template, {'NavSearchForm':NavSearchForm,'restaurant_list': restaurant_list, 'address_list': address_list, 'comment_list': comment_list, 'list': restaurant_address_rating_list})


class RestaurantDetailView(TemplateView):
    template = 'Customer/restaurant_detail.html'

    def get(self, request, *args, **kwargs):

        try:
            restaurant = Restaurant.objects.get(pk=kwargs['pk'])
        except ObjectDoesNotExist:
            #return HttpResponse('NO restaurant found.', status=status.HTTP_404_NOT_FOUND)
            return render(request,self.template)            

        address = Address.objects.get(restaurant=restaurant)
        dishestotal = Dish.objects.filter(restaurant=restaurant)
        dishes = dishestotal.extra(
            select={'total_like': 'liked/(liked+unliked)'},
            order_by=['-total_like']
        )[:3]
        dishcount = dishestotal.count()
        comment = list(Comment_R.objects.filter(restaurant=restaurant).order_by('-time'))
        ratetotal = Comment_R.objects.filter(restaurant=restaurant)
        ratecount = ratetotal.count()
        temp = 0


        for r in ratetotal:
            temp = temp + r.rating
        if ratecount == 0:
            rate = 0
        else:
            rate = temp / ratecount

        return render(request, self.template,
                      {'NavSearchForm':NavSearchForm, 'restaurant': restaurant, 'address': address, 'dishes': dishes, 'dishcount': dishcount,
                       'comment': comment, 'comment_form': CommentForm, 'rate': round(rate,1), 'ratecount': ratecount})

    def post(self, request, *args, **kwargs):
        user = request.user
        restaurant = Restaurant.objects.get(pk=kwargs['pk'])
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.restaurant = restaurant
            comment.time = datetime.datetime.now()
            comment.buyer =request.user
            comment.save()
            comment_form = CommentForm()

        address = Address.objects.get(restaurant=restaurant)
        dishesObject = Dish.objects.filter(restaurant=restaurant)
        dishes = dishesObject.extra(
            select={'total_like': 'liked/(liked+unliked)'},
            order_by=['-total_like']
        )[:3]
        comment = list(Comment_R.objects.filter(restaurant=restaurant).order_by('-time'))
        ratetotal = Comment_R.objects.filter(restaurant=restaurant)
        ratecount = ratetotal.count()
        temp = 0

        for r in ratetotal:
            temp = temp + r.rating
        if ratecount == 0:
            rate = 0
        else:
            rate = temp / ratecount

        return render(request, self.template,
                      {'NavSearchForm':NavSearchForm, 'restaurant': restaurant, 'address': address, 'dishes': dishes, 'dishcount': dishesObject.count(),
                       'comment': comment, 'comment_form': comment_form, 'rate': round(rate,1), 'ratecount': ratecount})

class DishListView(TemplateView):
    template = 'Customer/dishlist.html'

    def get(self, request, *args, **kwargs):
        restaurant = Restaurant.objects.get(pk=kwargs['pk'])
        dishes = Dish.objects.filter(restaurant=restaurant).extra(
            select={'total_like': 'liked/(liked+unliked)'},
            order_by=['-total_like']
        )

        ratetotal = Comment_R.objects.filter(restaurant=restaurant)
        ratecount = ratetotal.count()
        temp = 0
        
        entries = Dish.objects.filter(restaurant=restaurant, dishcategory='ent')
        entries_quantity = len(entries)
        mains = Dish.objects.filter(restaurant=restaurant, dishcategory='mai')
        mains_quantity = len(mains)
        desserts = Dish.objects.filter(restaurant=restaurant, dishcategory='des')
        desserts_quantity = len(desserts)
        drinks = Dish.objects.filter(restaurant=restaurant, dishcategory='drk')
        drinks_quantity = len(drinks)
        for r in ratetotal:
            temp = temp + r.rating
        if ratecount == 0:
            rate = 0
        else:
            rate = temp / ratecount

        return render(request, self.template,
                      {'NavSearchForm':NavSearchForm, 'restaurant': restaurant, 'dishes': dishes, 'rate': round(rate,1), 'ratecount': ratecount, 'entries_quantity':entries_quantity, 'mains_quantity':mains_quantity, 'desserts_quantity':desserts_quantity, 'drinks_quantity':drinks_quantity})
        # response.delete_cookie('dishes')
        # return response


class RestaurantAPIView(APIView):
    def get(self, request, pk, *args, **kwargs):
        try:
            return Response(RestaurantSerializer(Restaurant.objects.get(id=pk)).data)
        except ObjectDoesNotExist:
            raise  Http404

class DetailDish(APIView):
    def get_object(self, dish_id):

        try:
            return Dish.objects.get(pk=dish_id)
        except Dish.DoesNotExist:
            raise Http404

    def get(self, request, dish_id, formate=None):

        dish = self.get_object(dish_id)
        serializer = DishSerializer(dish)
        comment=DishComment.objects.filter(dish=dish)
        serializer2=DishCommentSerializer(comment,many=True)
        result=list()
        result.append(serializer.data)
        result.append(serializer2.data)
        return Response(result)        

class DetailDishLike(APIView):
    def get_object(self, dish_id):

        try:
            return Dish.objects.filter(pk=dish_id)
        except Dish.DoesNotExist:
            raise Http404

    def get(self, request, dish_id, formate=None):

        dish = self.get_object(dish_id)
        dish.update(liked=F('liked')+1)
        
        serializer = DishSerializer(Dish.objects.get(pk=dish_id))
        return Response(serializer.data)

class DetailDishUnlike(APIView):
    def get_object(self, dish_id):

        try:
            return Dish.objects.filter(pk=dish_id)
        except Dish.DoesNotExist:
            raise Http404

    def get(self, request, dish_id, formate=None):

        dish = self.get_object(dish_id)
        dish.update(unliked=F('unliked')+1)
        
        serializer = DishSerializer(Dish.objects.get(pk=dish_id))
        return Response(serializer.data)

class FilterView(APIView):
    def get_object(self):
        try:
            return Restaurant.objects.all()
        except Restaurant.DoesNotExist:
            raise Http404

    def post(self,request, *args, **kwargs):
        restaurant=self.get_object()
        address_list = Address.objects.all()
        comment_list = Comment_R.objects.all()
        # if request.data.get("category","")!="":
        #     restaurant=Restaurant.objects.filter(category=request.data.get("category",""))
        #     if request.data.get("Provide_Delivery",)=='true':
        #         restaurant=Restaurant.objects.filter(category=request.data.get("category",""),Provide_Delivery=request.data.get("Provide_Delivery",))
        #         if request.data.get("Children_Friendly",)=='true':
        #             restaurant=Restaurant.objects.filter(category=request.data.get("category",""),Provide_Delivery=request.data.get("Provide_Delivery",),Children_Friendly=request.data.get("Children_Friendly",))
        #             if request.data.get("Wifi",)=='true':
        #                 restaurant=Restaurant.objects.filter(category=request.data.get("category",""),Provide_Delivery=request.data.get("Provide_Delivery",),Children_Friendly=request.data.get("Children_Friendly",),Wifi=request.data.get("Wifi",))
        #                 if request.data.get("Vegan",)=='true':

OrderingSystem/Customer/templates/Customer/completeOrder.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
    <link rel="stylesheet" type="text/css" href="{% static 'Customer/orderCompletePage.css' %}"/>

    <script>

        window.addEventListener('load',function(event){

            var tr = document.getElementsByTagName("tr");

            if(tr.length > 3)
            {
                var number = (tr.length - 3) * 43 + 750;
                var heightPx = number + "px";
                document.getElementById("cart-container").style.height = heightPx;
            }



            var tr = document.getElementsByTagName("tr");
            var total = 0;
            for(var i = 1; i < tr.length; i++)
            {

                var td = tr[i].childNodes;
                //var p = td[3].innerHTML.substring(1, td[3].innerHTML.length);
            
                var p = td[3].innerHTML.substring(1, td[3].innerHTML.length);
                
                // p = (td[3].childNodes)[0].value.substring(1, (td[3].childNodes)[0].value.length)
                
                var t = parseInt(td[5].innerHTML) * parseFloat(p);
               
                total = total + t;
                td[7].innerHTML = "$" + Math.round(t * 100) / 100;
            }

            total = Math.round(total * 100) / 100;
            document.getElementById("totalPrice").innerHTML = "$" + total;


        });


    </script>

{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active"><a href=""> </a></li>
    </ul>

{% endblock nav_section %}

{% block context %}

    <div class="nav-bar row">

        <a class="website-logo" href="{% url 'Customer:homepage' %}">Home</a>
        >
        <a class="nav-restName" href="{% url 'Customer:resaurant_detail' r.id %}">{{ r.name }}</a>
        >
        <a class="nav-conf">Confirmation</a>

        <!-- <div>
            <a href="#">Login</a>
            <a href="#">Register</a>
        </div> -->
    </div>

    <div class="row" id="cart-container">


{% if order %}


        <p class="warning">
            Successful Order!
        </p>

        <div class="columns small-12">
            <div class="row">
                <div class="columns small-4">
                    <div class="rest-logo">
                        {% if r.image %}
                            <a href="#"><img src="{{ r.image.url }}"></a>
                        {% else %}
                            <a href="#"><img src="{% static 'Customer/image/orderPage1.jpeg' %}"></a>
                        {% endif %}
                    </div>

                    <div class="crst-info">
                        <a class="crst-name" title="{{ r.name }}" href="{% url 'Customer:resaurant_detail' r.id %}">{{ r.name }}</a>

                        <p class="crst-flavor">
                            {{r.get_category_display}}
                        </p>
                    </div>
                </div>


                <div class="columns small-8">
                    <ul>
                        <li class="flow-nav">Place an order</li>
                        <li class="flow-nav">Order's information</li>
                        <li class="flow-nav">Order completed</li>
                    </ul>
                    <img class="flow-nav-pic" src="{% static 'Customer/image/orderCompletePage.png' %}" width="300">
                </div>
            </div>

            <table style="width:100%">
                <tr class="order-table-title">
                    <td style="width:60%">Food Basket</td>
                    <td>Unit Price</td>
                    <td style="width:15%">Quantity</td>
                    <td>Total</td>
                </tr>

                {% for o in order_items %}
                    {% ifequal newOrder o.Order %}
                    <tr class="order-table-detail">
                        <td>{{ o.Dish.name }}</td>
                        <td>${{ o.Dish.price }}</td>
                        <td>{{ o.number }}</td>
                        <td></td>
                    </tr>
                    {% endifequal %}
                {% endfor %}
               
                
            </table>

            <div class="total-payment">
                <p class="order-table-total-amount" id="totalPrice" style="font-weight: bold;"><strong></strong></p>

                <p class="order-table-total-order">Amounts：</p>
            </div>

            <div class="personal-section">
                <p><b>Person: </b>{{ request.user.first_name }} {{ request.user.last_name }}</p>
            </div>

            <hr/>

            <div>
                <p><b>Phone Number: </b>{{ newOrder.buyer.phone }}</p>
            </div>

            <hr/>

            <div class="deliverTypeSection">
                {% if newOrder.delivery_type == 0 %}
                <p><b>Delivery Address:</b> Pick Up</p>
                {% else %}
                <p><b>Delivery Address: </b> {{ newOrder.location }}</p>
                {% endif %}
                
            </div>

            <hr/>

            <div>
                <p class="paymentP"><b>Payment Method: </b>Payment on delivery</p>
                
                
            </div>

            <hr/>


            <div>
                <a href="{% url 'accounts:orderPage' %}" class="button previousOrders">Previous Orders</a>

            </div>

{% else %}

<div class="row">
<div class="column small-2 noOrderPic">
    <img src="{% static 'Customer/image/orderCompletePage2.jpeg' %}" width="100" >
</div>

<div class="column small-7">
    <p class="noOrderP">You Haven't Order Yet!</p>

    <p>Please Order.</p>

</div>

</div>
{% endif %}
            

            <div>
                <a href="{% url 'Customer:homepage' %}" class="button goHomePageButton">Home</a>
            </div>
        </div>
    </div>

{% endblock context %}

OrderingSystem/Customer/templates/Customer/photos.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
    <link rel="stylesheet" type="text/css" href="{% static 'Customer/hotos.css' %}"/>
{% endblock page_style %}

{% block nav_section %}
{% endblock nav_section %}

{% block context %}




{% endblock context %}

OrderingSystem/Customer/templates/Customer/restaurant_detail1.html
{% extends "business/base.html" %}


{% block nav_section %}

    <ul class="right">
        <li class="active"><a href=""> </a></li>
    </ul>

{% endblock nav_section %}

{% block context %}
    <h1>Restaurant: {{ restaurant.name }}</h1>
    <dl class="display">
        <dt><b>msg:</b></dt>
        <dd>
            <div class="field">{{ restaurant.msg }}</div>
        </dd>
        <dt><b>image:</b></dt>
        <dd>
            <div class="field">{{ restaurant.image }}</div>
        </dd>
        <dt><b>Phone Number:</b></dt>
        <dd>
            <div class="field">{{ restaurant.phone }}</div>
        </dd>


    </dl>

    <ul>
        {% for p in dishes %}
            <li>{{ p.name }}</li>
        {% endfor %}
    </ul>





{% endblock context %}

OrderingSystem/Customer/templates/Customer/search_list.html
{% if results %}
    {% for restaurant in results %}
        <li>
            <a class="center" href="{% url 'Customer:resaurant_detail' restaurant.id %}">
                <span style=" font-weight: bold;">{{ restaurant.name }}</span>
                <p class="center">{{ restaurant.msg }}</p>
            </a>

        </li>
    {% endfor %}
{% endif %}

{% if dishresults %}
    {% for dish in dishlist %}
        <li>
            <a href="/{{ dish.r.id }}/dishlist#{{ dish.d.id }}">{{ 'Dish:' }} {{ dish.d.name }}</a>
        </li>
    {% endfor %}
{% endif %}

OrderingSystem/Customer/templates/Customer/search_result.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
    <link rel="stylesheet" type="text/css" href="{% static 'Customer/homepage.css' %}"/>
{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active">
        </li>
    </ul>
    <ul class="right">
        <li class="active"><a href="{% url 'Customer:homepage' %}">Back</a></li>
    </ul>
{% endblock nav_section %}
{% block context %}


    <fieldset class="columns small-10 small-centered ">
        <legend >About {{ count }} restaurants and {{ dishcount }} dishes:</legend>
        <!--restaurant list-->
        <div class="columns small-10 small-centered " id="middle-section" style="background-color: #FFFFFF;min-height: 2000px; padding-top: 20px;">

            <div class="row" id="has_result"> </div>
            <div class="columns small-12">
                {% if list %}
                    {% for r in list %}
                        <div class="restaurant_item row">
                            <!--left words-->
                            <div class="columns small-10 large-8">
                                <a href="{% url 'Customer:resaurant_detail' r.r.id %}" class="rest_name">{{ r.r.name }}</a>
                                <div style="color: #757575">Cuisine: {{r.r.get_category_display}}</div>
                                <div class="rest_address">{{r.address.0.city}}: {{r.address.0.address}} </div>
                                <div class="rest_tags">
                                    <span class="round secondary label" ><a href="{% url 'Customer:resaurant_detail' r.r.id %}dishlist">Menu</a></span>
                                    <span class="round secondary label" ><a href="{% url 'Customer:resaurant_detail' r.r.id%}#photos">Pictures</a></span>
                                    <span class="round secondary label" ><a href="{% url 'Customer:resaurant_detail' r.r.id%}#comment">Comment</a></span>
                                </div>
                            </div>
                            <!--right pic-->
                            <div class="columns small-2 large-4 right rating" >
                                <div class="row">
                                    <div class="small-12 columns rating_section">
                                        <div class="row rating_section">
                                            <div class="info round label small-centered rate_label" >{{r.rating}}</div>
                                            <div class="vote">{{r.vote}} votes</div>
                                        </div>
                                    </div>
                                    <div class="column small-12">
                                        {%if r.r.image %}
                                            <span class="rest_pic" ><img src=" {{ r.r.image.url }} "
                                                                         height="60" width="60"></span>
                                        {%endif %}
                                        {% for one in dishes %}
                                            {% if one.image %}
                                                <span class="dish-pic" style="cursor:pointer;"><img src="{{ one.image.url }}" height="60"width="60"></span>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}


                {% else %}
                    <p>No Restaurants are available.</p>
                {% endif %}
            </div>





            <div class="columns small-12">
                {% if dishlist %}
                    {% for dish in dishlist %}
                        <div class="restaurant_item row">
                            <!--left words-->
                            <div class="columns small-10 large-8">
                                <a class="medium"
                                   href="/{{ dish.r.id }}/dishlist#{{ dish.d.id }}">{{ 'Dish:' }} {{ dish.d.name }}</a>

                                <div class="rest_tags">
                                    <span><h>{{dish.d.description}}</h></span>
                                </div>
                            </div>
                            <!--right pic-->
                            <div class="columns small-2 large-4 right rating" >
                                <div class="row">
                                    <div class="small-12 columns rating_section">
                                        <div class="row rating_section">
                                            {%if dish.d.image %}
                                                <span class="rest_pic" ><img src=" {{ dish.d.image.url }} "
                                                                             height="60" width="60"></span>
                                            {%endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}

                {% else %}
                    <p>No Dishes are available.</p>
                {% endif %}
            </div>

        </div>

        </div>

    </fieldset>

{% endblock context %}