OrderingSystem/Customer/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from Customer import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='homepage'),
    #url(r'^restaurant$', views.RestaurantView.as_view(), name='restaurantPage'),
    url(r'^(?P<pk>[0-9]+)/order$', login_required(views.OrderView.as_view()), name='orderPage'),
    url(r'^(?P<pk>[0-9]+)/complete$', login_required(views.CompleteOrderView.as_view()), name='completeOrder'),
    url(r'^restaurant/(?P<pk>[0-9]+)/$', views.RestaurantAPIView.as_view(), name='resaurant_detail_api'),
    url(r'^(?P<pk>[0-9]+)/$', views.RestaurantDetailView.as_view(), name='resaurant_detail'),
    url(r'^(?P<pk>[0-9]+)/dishlist$', views.DishListView.as_view(), name='resaurant_dishlist'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/$', views.DetailDish.as_view(), name='resaurant_detaildish'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/like$', views.DetailDishLike.as_view(), name='resaurant_detaildish_like'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/unliked$', views.DetailDishUnlike.as_view(), name='resaurant_detaildish_unlike'),
    url(r'^filter$', views.FilterView.as_view(), name='resaurant_filter'),
    url(r'^cookie/$',views.CookieView.as_view(),name="order_cookie"),
    url(r'^searchresult/$',views.search.as_view(),name="searchpage"),
    )

#urlpatterns = format_suffix_patterns(urlpatterns)

OrderingSystem/OrderingSystem/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.forms import RegistrationForm
from registration.backends.default.views import RegistrationView

urlpatterns = patterns(
    '',
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationForm), name='registration_register'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^business/', include('business.urls', namespace='business')),
    url(r'^', include('Customer.urls', namespace='Customer')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OrderingSystem/business/urls.py
from django.conf.urls import patterns
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required

import views

urlpatterns = patterns(
    '',
    url(r'^$', login_required(views.RestaurantView.as_view()), name='RestaurantPage'),
    url(r'^report$', login_required(views.ReportView.as_view()), name='ReportPage'),
    url(r'^edit$', login_required(views.EditRestaurantView.as_view()), name='EditRestaurantPage'),
    url(r'^dish/(?P<pk>[0-9]+)$', login_required(views.DishView.as_view()), name='DishPage'),
    url(r'^order/(?P<pk>[0-9]+)$', login_required(views.OrderView.as_view()), name='OrderPage'),
    url(r'^order$', login_required(views.OrderListView.as_view()), name='OrderListPage'),
    url(r'^order/inprogress/$', login_required(views.InprocessOrderView.as_view()), name='InprogressOrderPage'),
    url(r'^order/complete/$', login_required(views.CompleteOrderView.as_view()), name='CompleteOrderPage'),
    url(r'^order/cancel/$', login_required(views.CanceledOrderView.as_view()), name='CancelOrderPage'),
    url(r'^signup$', views.SignUpView.as_view(), name='SignUpPage'),
    url(r'^account/(?P<pk>[0-9]+)$', login_required(views.BuyerView.as_view()), name='BuyerPage'),
    )

OrderingSystem/business/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse

from geopy.geocoders.googlev3 import GoogleV3
from geopy.exc import GeocoderQueryError
from urllib2 import URLError

from OrderingSystem import settings


class Restaurant(models.Model):
    baseUser = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField('Restaurant Name', max_length=50)
    # category = models.CharField('Food Type', max_length=50, blank=True)
    msg = models.TextField('Description', blank=True, null=True)
    image = models.FileField(upload_to='restaurant/%Y/%m/%d', null=True, blank=True)
    phone_regex = RegexValidator(regex=r'^[+|\d][0-9() -]*\d$', message="Please enter a correct phone number.")
    phone = models.CharField('Business Phone', validators=[phone_regex], null=True, blank=True, max_length=20)
    Provide_Delivery = models.BooleanField(default=False)
    Children_Friendly = models.BooleanField(default=False)
    Wifi = models.BooleanField(default=False)
    Vegan = models.BooleanField(default=False)
    Gluten_Free = models.BooleanField(default=False)

    # time reference
    createdAt = models.DateTimeField(auto_now_add=1, auto_now=0)
    lastAccessAt = models.DateTimeField(auto_now=1, auto_now_add=0)
    food_choices = (
        ('ff', 'FastFood'),
        ('cns', 'Chinese'),
        ('jpf', 'Japanese'),
        ('wst', 'Western'),
    )
    category = models.CharField('Food Type', max_length=10, choices=food_choices, default='cns')

    time_choices = (
        ('06:00', '06:00'),
        ('07:00', '07:00'),
        ('08:00', '08:00'),
        ('09:00', '09:00'),
        ('10:00', '10:00'),
        ('11:00', '11:00'),
        ('12:00', '12:00'),
        ('13:00', '13:00'),
        ('14:00', '14:00'),
        ('15:00', '15:00'),
        ('16:00', '16:00'),
        ('17:00', '17:00'),
        ('18:00', '18:00'),
        ('19:00', '19:00'),
        ('20:00', '20:00'),
        ('21:00', '21:00'),
        ('22:00', '22:00'),
        ('23:00', '23:00'),
        ('24:00', '24:00'),
        ('01:00', '01:00'),
        ('02:00', '02:00'),
        ('03:00', '03:00'),
        ('04:00', '04:00'),
        ('05:00', '05:00'),
    )
    opentime = models.CharField('Open Time', max_length=10, choices=time_choices, default='08:00')
    closetime = models.CharField('Close Time', max_length=10, choices=time_choices, default='22:00')

    def get_absolute_url(self):
        return reverse('business:RestaurantPage')


class Address(models.Model):
    restaurant = models.ForeignKey(Restaurant, related_name="address")
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=20)
    zipcode = models.CharField(max_length=10)
    # gis = gis_models.GeoManager()

    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    # location = gis_models.PointField(u"longitude/latitude", geography=True, blank=True, null=True)

    def __unicode__(self):
        return str(self.latitude) + " " + str(self.longitude)

    def save(self, **kwargs):
        address = u'%s %s, %s %s' % (self.address, self.city, self.state, self.zipcode)
        address = address.encode('utf-8')
        try:
            response = GoogleV3().geocode(address)

        except (URLError, GeocoderQueryError, ValueError):
            pass
        else:
            if response:
                _, coordinates = response
                self.latitude = coordinates[0]
                self.longitude = coordinates[1]
            else:
                self.latitude = None
                self.longitude = None
                # point = "POINT(%s %s)" % (coordinates[1], coordinates[0])
                # self.location = geos.fromstr(point)

        super(Address, self).save()


class Dish(models.Model):
    restaurant = models.ForeignKey(Restaurant)
    name = models.CharField(max_length=50)
    price = models.FloatField()
    image = models.FileField(upload_to='dishes/%Y/%m/%d', blank=True, null=True)
    liked = models.IntegerField(default=0)
    unliked = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)

    type_choices = (
        ('ent', 'Entries'),
        ('mai', 'Main'),
        ('des', 'Dessert'),
        ('drk', 'Drinks'),
    )
    dishcategory = models.CharField('Dish Type', max_length=10, choices=type_choices, default='ent')


class RestaurantComment(models.Model):
    comment = models.TextField()
    restaurant = models.ForeignKey(Restaurant)


class DishComment(models.Model):
    comment = models.TextField()
    dish = models.ForeignKey(Dish)

OrderingSystem/business/forms.py
__author__ = 'JC'

from django import forms
from models import Restaurant, Address, Dish


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        exclude = ['baseUser', ]
        help_texts = {
            'name': 'Everybody can see your restaurant name.',
            'phone': 'Giving out your business phone number is not mandatory, but it is very important to customers.'
        }

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['restaurant', 'latitude', 'longitude']


class DishForm(forms.ModelForm):
    class Meta:
        model = Dish
        exclude = ['restaurant', 'status', 'liked', 'unliked']

OrderingSystem/business/templates/business/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ordering System</title>
    <link rel="stylesheet" type="text/css" href="{% static 'foundation-5.5.2/css/foundation.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'foundation-icons/foundation-icons.css' %}"/>


</head>
<body>
<script>

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=410206499181926";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    !function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https';
        if (!d.getElementById(id)) {
            js = d.createElement(s);
            js.id = id;
            js.src = p + '://platform.twitter.com/widgets.js';
            fjs.parentNode.insertBefore(js, fjs);
        }
    }(document, 'script', 'twitter-wjs');
</script>

<div class="contain-to-grid" style="padding-top: 10px; padding-bottom: 10px;">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1 style="font-size: 35px;"><a href="{% url 'Customer:homepage' %}">G-Order</a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>


        <section class="top-bar-section">
            <ul class="right">
                {% if request.user.is_authenticated %}
                    <li class="has-dropdown">
                        <a href="{% url 'accounts:profilePage' %}" style="font-size: 20px; color: white;">
                            {% if request.user.image %}
                                <img src="{{ request.user.image.url }}"
                                     style="height: 40px; width: auto; border-radius: 20px;">
                            {% endif %}
                            {% if request.user.first_name or request.user.last_name %}
                                {{ request.user.first_name }} {{ request.user.last_name }}
                            {% else %}
                                {{ request.user.username }}
                            {% endif %}
                        </a>
                        <ul class="dropdown">
                            <li><a href="{% url 'accounts:profilePage' %}">Personal Profile</a></li>
                            {% if request.user.restaurant %}
                                <li><a href="{% url 'business:RestaurantPage' %}">{{ request.user.restaurant.name }}</a>
                                </li>
                            {% endif %}
                            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                        </ul>
                    </li>

                {% else %}
                    <li><a href="{% url 'auth_login' %}">Login / Sign up</a></li>
                {% endif %}
            </ul>
            {% block nav_section %}{% endblock nav_section %}
        </section>
    </nav>
</div>

{% block context %}{% endblock context %}

<script src="{% static 'foundation-5.5.2/js/vendor/jquery.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/vendor/modernizr.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation/foundation.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation.min.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation/foundation.topbar.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation/foundation.reveal.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation/foundation.tooltip.js' %}"></script>
<script src="{% static 'foundation-5.5.2/js/foundation/foundation.dropdown.js' %}"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>

<script>
    $(document).foundation();
</script>

{% block javascript %}{% endblock javascript %}

</body>
</html>

OrderingSystem/business/templates/business/buyerprofile.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block nav_section %}



{% endblock nav_section %}

{% block context %}
    <div class="row">



             <div class="columns small-6 small-centered">
                <fieldset>
                    <legend>Detail</legend>
                    <div class="row">
                        First Name: {{ order.buyer.first_name }}

                    </div>
                    <div class="row">
                        Last Name: {{ order.buyer.last_name }}

                    </div>
                    <div class="row">
                        Email: {{ order.buyer.email }}

                    </div>

                    <div class="row">
                        Phone Number: {{ order.buyer.phone }}
                    </div>
                </fieldset>

            </div>

             <div class="columns small-6 small-centered">
                <fieldset>
                    <legend>Order History</legend>

                   {% for order in orders %}

                        <div class="row">
                        <a href="{% url 'business:OrderPage' order.id %}"> {{ "Order: " }}{{ order.id }}{{ " Time: " }}{{ order.time }}</a>
                        </div>

                {% endfor %}
                </fieldset>

            </div>


    </div>

{% endblock context %}

OrderingSystem/business/templates/business/cancelorder.html
{% extends "Customer/base.html" %}


{% block nav_section %}


{% endblock nav_section %}


{% block context %}



    <div class="row">
        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>Cancelled:</legend>
            <ul>
                {% for order in canorders %}

                    <li><a class="medium"
                           href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                    </li>
                {% endfor %}

            </ul>
        </fieldset>

    </div>




{% endblock context %}

OrderingSystem/business/templates/business/completeorder.html
{% extends "Customer/base.html" %}


{% block nav_section %}


{% endblock nav_section %}


{% block context %}



    <div class="row">
        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>Completed:</legend>
            <ul>
                {% for order in finorders %}

                    <li><a class="medium"
                           href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                    </li>
                {% endfor %}

            </ul>
        </fieldset>

    </div>




{% endblock context %}

OrderingSystem/business/templates/business/detail.html
{% extends "Customer/base.html" %}

{% block nav_section %}

    <ul class="right">
        <li class="active"><a href=""> </a></li>
    </ul>

{% endblock nav_section %}


{% block context %}
    <div class="row">
        {% if restaurant.image %}
            <div class="columns small-12"
                 style="width: 100%; height: 250px; overflow: hidden; background-size: cover; background-position: center; background-image: url('{{ restaurant.image.url }}');"></div>
        {% endif %}

        <div class="columns medium-8 small-centered medium-uncentered">
            <h3>{{ restaurant.name }} <a class="button round" style="padding: 10px;"
                                         href="{% url 'business:EditRestaurantPage' %}">Edit</a></h3>

            <h4>
                <small>{{ restaurant.msg|linebreaks }}</small>
            </h4>
            <div>
                <b>Address: </b>{{ address.address }} {{ address.city }}, {{ address.state }}, {{ address.zipcode }}
            </div>
            <div><b>Business Phone: </b>{{ restaurant.phone }}</div>
            <div><b>Open Time: </b>{{ restaurant.opentime }}</div>
            <div><b>Close Time: </b>{{ restaurant.closetime }}</div>
            <div class="row">
                <div class="columns small-8" style="margin-top: 20px;">
                    <span class="fb-share-button" data-href="http://cmpt470.csil.sfu.ca:8014/{{ restaurant.id }}"
                          data-layout="button" style="top: -6px;"></span>
                    <a href="https://twitter.com/share" class="twitter-share-button"
                       data-url="http://cmpt470.csil.sfu.ca:8014/{{ restaurant.id }}" data-count="none">Tweet</a>
                    <span class="g-plus" data-action="share" data-annotation="none"></span>
                </div>
                <div class="columns small-4">
                    <a class="button medium radius alert right" style="padding: 10px;"
                       href="{% url 'business:OrderListPage' %}">View Orders</a>
                </div>
            </div>
        </div>

        <div class="columns medium-4 small-centered medium-uncentered" style="">
            <div id="map" style="height: 250px; margin-top: 10px;"></div>
        </div>
    </div>

    <div class="row">
        <div class="columns small-12">
            <fieldset>
                <legend>
                    Dishes:
                </legend>
                <ul class="small-block-grid-2 medium-block-grid-4 large-block-grid-6">
                    {% for dish in dishes %}
                        <li>
                            {% if dish.image %}
                                <a class="th" href="{% url 'business:DishPage' dish.id %}">
                                    <img src="{{ dish.image.url }}">
                                </a>
                            {% endif %}
                            <div>
                                <a class="left" href="{% url 'business:DishPage' dish.id %}">{{ dish.name }}</a>
                                <span class="right fi-price-tag">{{ dish.price }}</span>
                            </div>
                        </li>
                    {% endfor %}
                <li><a id="modalLink" data-reveal-id="AddDishModal" href="#" class="button success round text-center"
                   style="padding: 10px;">Add a Dish</a></li>
                </ul>

            </fieldset>
        </div>
    </div>

    <div id="AddDishModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true"
         role="dialog">
        <form action="{% url 'business:RestaurantPage' %}" method="post" enctype="multipart/form-data">
            <fieldset>
                <legend>Add a dish to your restaurant:</legend>
                {% csrf_token %}
                {{ dish_form }}
                <input class="small button success right" type="submit" value="Add"/>
            </fieldset>
        </form>
    </div>

    <div id="fb-root"></div>

{% endblock context %}

{% block javascript %}
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            {% if address.latitude == None or address.longitude == None %}
                document.getElementById('map').removeAttribute('style');
                document.getElementById('map').innerHTML = '<fieldset><h4 class="subheader text-center">Address is invalid. <br>No location information.</h4></fieldset>'
            {% else %}
                var latlng = new google.maps.LatLng({{ address.latitude }}, {{ address.longitude }});

                var mapOptions = {
                    zoom: 15,
                    center: latlng,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById('map'), mapOptions);

                latlng = new google.maps.LatLng("{{ address.latitude }}", "{{ address.longitude }}");
                var marker = new google.maps.Marker({
                    position: latlng,
                    map: map,
                    title: "{{ restaurant.name }}"
                });

                var infoWindow = new google.maps.InfoWindow({
                    content: '<div>{{ restaurant.name }}</div>'
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infoWindow.open(map, marker);
                });
            {%  endif %}
        });
    </script>

{% endblock javascript %}

OrderingSystem/business/templates/business/dish_detail.html
{% extends "Customer/base.html" %}

{% block nav_section %}

    <ul class="right">
        <li class="active"><a href="{% url 'business:RestaurantPage' %}">Cancel</a></li>
    </ul>

{% endblock nav_section %}

{% block context %}


    <div class="row">
        <div class="columns small-8 small-centered">
            <form action="{% url 'business:DishPage' dish.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ dish_form }}
                <input class="small button success right" type="submit" value="Update"/>

            </form>
        </div>
    </div>

{% endblock context %}

OrderingSystem/business/templates/business/edit_restaurant_page.html
{% extends "Customer/base.html" %}

{% block nav_section %}

    <ul class="right">
        <li class="active"><a href=""> </a></li>
    </ul>

{% endblock nav_section %}

{% block context %}

    <div class="row">
        <form action="{% url 'business:EditRestaurantPage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="columns small-11 large-6 small-centered large-uncentered">
                    <fieldset>
                        <legend>Restaurant Detail</legend>
                        {% for field in restaurant_form %}
                            <label class="{{ field.help_text|yesno:"has-tip," }}{{ field.errors|yesno:" error," }}"
                                    {% if field.help_text %}
                                   data-tooltip aria-haspopup="true"
                                   title="{{ field.help_text }}"{% endif %}>
                                {{ field.label }}
                                <small>{{ field.field.required|yesno:'required,' }}</small>
                                {{ field }}
                            </label>
                            {% if field.errors %}
                                <small class="error">{{ field.errors }}</small>
                            {% endif %}
                        {% endfor %}
                    </fieldset>
                </div>

                <div class="columns small-11 large-6 small-centered large-uncentered">
                    <fieldset>
                        <legend>Restaurant Address</legend>
                        {{ address_form }}
                        {{ zipcode_form }}
                    </fieldset>
                </div>
            </div>
            <div class="row">
                <div class="columns small-11 large-12">
                    <ul class="button-group round right">
                        <li><input class="small button success" type="submit" value="Submit"/></li>
                        <li><a class="small button" href="{% url 'business:RestaurantPage' %}">Cancel</a></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>

{% endblock context %}

OrderingSystem/business/templates/business/inprocessorder.html
{% extends "Customer/base.html" %}


{% block nav_section %}


{% endblock nav_section %}


{% block context %}



    <div class="row">
        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>In Progress:</legend>
            <ul>
                {% for order in progorders %}

                    <li><a class="medium"
                           href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                    </li>
                {% endfor %}

            </ul>
        </fieldset>

    </div>




{% endblock context %}

OrderingSystem/business/templates/business/order.html
{% extends "Customer/base.html" %}

{% block nav_section %}

{% endblock nav_section %}


{% block context %}

<head> <meta http-equiv="refresh" content="10" /> </head>
    <div class="row">
        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>In Progress:</legend>
            <ul>
                {% for order in progorders %}

                    {% if order.status == 'prog' %}
                        <li style="list-style-type: none;">
                            <a class="medium"
                               href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

            </ul>
            <a class="right" href="{% url 'business:InprogressOrderPage' %}">More</a>

        </fieldset>

        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>Completed</legend>
            <ul>
                {% for order in finorders %}
                    {% if order.status == 'fin' %}
                        <li style="list-style-type: none;">
                            <a class="medium"
                               href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

            </ul>
            <a class="right" href="{% url 'business:CompleteOrderPage' %}">More</a>
        </fieldset>

        <fieldset class="columns small-11 large-9 small-centered large-centered">
            <legend>Cancelled</legend>
            <ul>
                {% for order in canorders %}
                    {% if order.status == 'can' %}
                        <li style="list-style-type: none;">
                            <a class="medium"
                               href="{% url 'business:OrderPage' order.id %}">{{ 'Order:' }} {{ order.id }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

            </ul>
            <a class="right" href="{% url 'business:CancelOrderPage' %}">More</a>
        </fieldset>
    </div>


{% endblock context %}

OrderingSystem/business/templates/business/order_detail.html
{% extends "Customer/base.html" %}

{% block nav_section %}


{% endblock nav_section %}


{% block context %}
    <fieldset class="columns small-6 small-centered ">
        <legend >Order Detail:</legend>

        <ul>
            <h>Dishes:</h>
            {% for dish in dish_set %}
                <li style="list-style-type: none;">

                    <a href="{% url 'business:DishPage' dish.id %}"> {{ dish.name }}</a>
                    {% for oitem in orderitem %}
                        {% if oitem.Dish == dish %}
                            <h class="right"> {{ dish.price }}{{ '$ ×' }}{{ oitem.number }}</h>
                        {% endif %}

                    {% endfor %}
                </li>
            {% endfor %}
        </ul>

        <ul>
            <h>Buyer:</h>
            <li style="list-style-type: none;">
                <a href="{% url 'business:BuyerPage' order.id %}"> {{ order.buyer}}</a>
            </li>
        </ul>

        <ul>
            <h>Delivery Type:</h>
            <li style="list-style-type: none;">
                {% for key, value in deliverytype.items %}
                    {% if key == order.delivery_type %}
                        <p>{{ value }}</p>
                    {% endif %}
                {% endfor %}
            </li>
        </ul>

        <ul>
            <h>Payment Status:</h>
            <li style="list-style-type: none;">
                {% for key, value in paytype.items %}
                    {% if key == order.paid %}
                        <p>{{ value }}</p>
                    {% endif %}
                {% endfor %}
            </li>
        </ul>


        {% if order.location %}


            <ul>
                <h>Location:</h>
                <li style="list-style-type: none;">

                    {{ order.location }}

                </li>
            </ul>


        {% endif %}
        <ul>
            <h>Order Time:</h>
            <li style="list-style-type: none;">

                {{ order.time }}

            </li>
        </ul>

        <ul>
            <h>Total Price:</h>
            <li style="list-style-type: none;">

                {{ order.total_price }}

            </li>
        </ul>


        <ul>
            <h>Discount:</h>
            <li style="list-style-type: none;">

                {{ order.discount }}

            </li>
        </ul>
    </fieldset>

    <div class="row">
        <div class="columns small-8 small-centered">
            <form action="{% url 'business:OrderPage' order.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ order_form }}
                <input class="small button success right" type="submit" value="Update"/>

            </form>
        </div>

    </div>




{% endblock context %}