OrderingSystem/Customer/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns
from Customer import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='homepage'),
    #url(r'^restaurant$', views.RestaurantView.as_view(), name='restaurantPage'),
    url(r'^(?P<pk>[0-9]+)/order$', login_required(views.OrderView.as_view()), name='orderPage'),
    url(r'^(?P<pk>[0-9]+)/complete$', login_required(views.CompleteOrderView.as_view()), name='completeOrder'),
    url(r'^restaurant/(?P<pk>[0-9]+)/$', views.RestaurantAPIView.as_view(), name='resaurant_detail_api'),
    url(r'^(?P<pk>[0-9]+)/$', views.RestaurantDetailView.as_view(), name='resaurant_detail'),
    url(r'^(?P<pk>[0-9]+)/dishlist$', views.DishListView.as_view(), name='resaurant_dishlist'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/$', views.DetailDish.as_view(), name='resaurant_detaildish'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/like$', views.DetailDishLike.as_view(), name='resaurant_detaildish_like'),
    url(r'^dishlist/(?P<dish_id>[0-9]+)/unliked$', views.DetailDishUnlike.as_view(), name='resaurant_detaildish_unlike'),
    url(r'^filter$', views.FilterView.as_view(), name='resaurant_filter'),
    url(r'^cookie/$',views.CookieView.as_view(),name="order_cookie"),
    url(r'^searchresult/$',views.search.as_view(),name="searchpage"),
    )

#urlpatterns = format_suffix_patterns(urlpatterns)

OrderingSystem/OrderingSystem/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.forms import RegistrationForm
from registration.backends.default.views import RegistrationView

urlpatterns = patterns(
    '',
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=RegistrationForm), name='registration_register'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^business/', include('business.urls', namespace='business')),
    url(r'^', include('Customer.urls', namespace='Customer')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OrderingSystem/accounts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from views import modal_login

import views

urlpatterns = patterns(
    '',
    url(r'^$', login_required(views.ProfileView.as_view()), name='profilePage'),
    url(r'^activities/$', login_required(views.ActivityView.as_view()), name='activityPage'),
    url(r'^modal-login/$', modal_login, {'template_name': 'registration/modal-login.html'}, name='modal_login'),
    url(r'^success', login_required(views.LoginSuccessView.as_view()), name='loginSuccessPage'),
    url(r'^orders/$', login_required(views.CustomerOrderView.as_view()), name='orderPage'),
    url(r'^orders/(?P<pk>[0-9]+)$', login_required(views.Detail.as_view()), name='orderdetail'),
    )

OrderingSystem/Customer/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from OrderingSystem import settings


class Order(models.Model):
    restaurant = models.ForeignKey('business.Restaurant', related_name='restaurant')
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='order')
    time = models.DateTimeField()
    location = models.CharField(max_length=200)
    delivery_type = models.IntegerField()
    total_price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.FloatField()
    paid = models.BooleanField(default=False)

    status_choices = (
        ('can', 'Cancelled'),
        ('prog', 'In Progress'),
        ('fin', 'Complete'),
    )
    status = models.CharField(max_length=10, choices=status_choices, default='prog')

    def __unicode__(self):
        return self.restaurant.name + ": " + str(self.id)


class OrderItem(models.Model):
    Order = models.ForeignKey(Order, related_name='orderitem')
    Dish = models.ForeignKey('business.Dish')
    restaurant = models.ForeignKey('business.Restaurant')
    number = models.IntegerField(validators=[MinValueValidator(0)])


class Comment_R(models.Model):
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_r')
    restaurant = models.ForeignKey('business.Restaurant')
    text = models.TextField()
    time = models.DateTimeField()
    rating = models.FloatField(validators=[MinValueValidator(1.0), MaxValueValidator(5.0)])

OrderingSystem/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import RegexValidator


class CustomUser(AbstractUser):
    phone_regex = RegexValidator(regex=r'^[+|\d][0-9() -]*\d$', message="Please enter a correct phone number.")
    phone = models.CharField('Phone Number', validators=[phone_regex], null=True, blank=True, max_length=20)
    image = models.FileField('Profile Picture', upload_to='customer/%Y/%m/%d', null=True, blank=True)

    objects = UserManager()

OrderingSystem/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from registration.users import UserModel, UsernameField

from models import CustomUser

class RegistrationForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = UserModel()
        fields = (UsernameField(), "first_name", "last_name", "email", "phone", "image")

        help_texts = {
            'email': 'You will need to activate the account with this email.',
        }

    def clean_email(self):
        if CustomUser.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = UserModel()
        fields = (UsernameField(), "first_name", "last_name", "email", "phone", "image")
        help_texts = {
            UsernameField(): 'The username is for logging in',
            'email': 'Your email is the only prove of identification.',
        }

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

OrderingSystem/accounts/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.sites.shortcuts import get_current_site
from django.forms.util import ErrorList
from Customer.models import *
from django.core.exceptions import ObjectDoesNotExist
import operator
from forms import UserUpdateForm
from accounts.models import CustomUser
# Create your views here.


class ProfileView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'accounts/profile.html', {'userUpdateForm': UserUpdateForm(instance=request.user)})

    def post(self, request, *args, **kwargs):
        updateForm = UserUpdateForm(request.POST, request.FILES, instance=request.user)
        if updateForm.is_valid():
            email = updateForm.cleaned_data['email']
            users = CustomUser.objects.filter(email=email)
            if len(users) >= 1 and users[0] != request.user:
                errors = updateForm._errors.setdefault("email", ErrorList())
                errors.append(u"This email has been register with another account.")
            else:
                updateForm.save();
                updateForm = UserUpdateForm(instance=request.user)
        return render(request, 'accounts/profile.html', {'userUpdateForm': updateForm})

class ActivityView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, 'accounts/activity.html')

class CustomerOrderView(TemplateView):
    def get(self, request, *args, **kwargs):
        user = request.user
        try:
            orders = Order.objects.filter(buyer=user).order_by('-time')
        except ObjectDoesNotExist:
            return HttpResponse('There is no order exist.', status=404)
        return render(request, 'accounts/orders.html', {'orders': orders})

class Detail(TemplateView):
    def get(self, request, *args, **kwargs):
        user = request.user
        try:
            orders = Order.objects.filter(buyer=user)
            order = Order.objects.get(buyer=user, pk=kwargs['pk'])
        except ObjectDoesNotExist:
            return HttpResponse('There is no order exist.', status=404)

        Oitem = OrderItem.objects.filter(Order = order)
        dish_set = set()
        count = 0
        dish_list = []
        while (count<len(Oitem)):
            dish_set.add(Oitem[count].Dish)
            oneList = {}
            oneList['r'] = Oitem[count].restaurant
            oneList['d'] = Oitem[count].Dish
            oneList['n'] =  Oitem[count].number
            dish_list.append(oneList)
            count = count + 1

        dictionary_delivery_type = {0: 'PickUp', 1: 'Home Delivery Service'}
        payment_status = {True: 'Paid', False: 'Not Paid'}

        return render(request, 'accounts/orderdetail.html', { 'dishlist':dish_list,'order': order, 'dish_set': dish_set, 'deliverytype': dictionary_delivery_type, 'orderitem': Oitem, 'paytype': payment_status})

class LoginSuccessView(TemplateView):
    def get(self, request, *args, **kwargs):
        return HttpResponse('You have successful logged in.')

@sensitive_post_parameters()
@csrf_protect
@never_cache
def modal_login(request, template_name='registration/login.html',
                redirect_field_name=REDIRECT_FIELD_NAME,
                authentication_form=AuthenticationForm,
                current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url('accounts:loginSuccessPage')

            # Okay, security check complete. Log the user in.
            login(request, form.get_user())

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)

OrderingSystem/accounts/templates/accounts/activity.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active">
            <a href=""></a></li>
    </ul>

{% endblock nav_section %}

{% block context %}
    <div class="row">
        <fieldset>
            <legend>Activity</legend>
            <div class="row">
                <ul class="text-center stack-for-small round button-group">
                    <li><a class="button success" href="{% url 'accounts:orderPage' %}">View More Orders</a>
                    </li>
                    {% if request.user.restaurant %}
                        <li><a class="button"
                               href="{% url 'business:RestaurantPage' %}">Manage {{ request.user.restaurant.name }}</a>
                        </li>
                    {% else %}
                        <li><a class="button success" href="{% url 'business:SignUpPage' %}">start a
                            restaurant?</a></li>
                    {% endif %}

                </ul>
            </div>
            <hr>
            <div class="row" data-equalizer>
                <div class="columns medium-10 large-8 medium-centered" style="border: 1px dashed gray;" data-equalizer-watch>
                    <ul class="tabs" data-tab role="tablist">
                        <li class="tab-title active" role="presentation">
                            <a href="#order_history" role="tab" tabindex="0" aria-selected="true"
                               aria-controls="order_history">Order
                                History</a></li>
                        <li class="tab-title" role="presentation">
                            <a href="#comment_history" role="tab" tabindex="0" aria-selected="false"
                               aria-controls="comment_history">Comment
                                History</a>
                        </li>
                    </ul>
                    <div class="tabs-content" style="overflow-y: scroll; max-height: 400px;" data-equalizer>
                        <section role="tabpanel" aria-hidden="false" class="content active" id="order_history"
                                 data-equalizer-watch>
                            {% if not request.user.order.all %}
                                <h4>No order history.</h4>
                            {% else %}
                                {% for order in request.user.order.all %}
                                    <div class="panel">
                                        <ul class="small-block-grid-3">
                                            <li>
                                                <small>Restaurant:</small>
                                                <a href="{% url 'Customer:resaurant_detail' order.restaurant.id %}">{{ order.restaurant.name }}</a>
                                            </li>

                                            <li>
                                                <small>Order Status:</small>
                                                {{ order.get_status_display }}
                                                <br>
                                                <small>Order Time:</small>
                                                {{ order.time|time }}
                                            </li>

                                            <li>
                                                <small>Total:</small>
                                                ${{ order.total_price }} ({{ order.paid|yesno:"Paid, Un-paid" }})
                                                <br>
                                                <a class="right" href="{% url 'accounts:orderdetail' order.id %}">View
                                                    Detail</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </section>
                        <section role="tabpanel" aria-hidden="true" class="content" id="comment_history"
                                 data-equalizer-watch>
                            {% if not request.user.comment_r.all %}
                                <h4>No comment history.</h4>
                            {% else %}
                                {% for comment in request.user.comment_r.all %}
                                    <div class="panel">
                                        <ul class="small-block-grid-3">
                                            <li>
                                                <small>Restaurant:</small>
                                                <a href="{% url 'Customer:resaurant_detail' comment.restaurant.id %}">{{ comment.restaurant.name }}</a>
                                            </li>
                                            <li>
                                                <small>Rating:</small>
                                                {{ comment.rating }}
                                            </li>
                                            <li>
                                                {{ comment.time|time }}
                                            </li>
                                        </ul>
                                        <small>Comment:</small>
                                        <div class="">
                                            {{ comment.text }}
                                        </div>
                                    </div>

                                {% endfor %}

                            {% endif %}
                        </section>
                    </div>
                </div>
{#                <div class="columns medium-4" style="border: 1px dashed gray;" data-equalizer-watch>#}
{#                    <h2>Empty space<br>#}
{#                        <small>Put what ever you like here.</small>#}
{#                    </h2>#}
{#                </div>#}
            </div>
        </fieldset>
    </div>

{% endblock context %}

{% block javascript %}
    <script>
        {% if userUpdateForm.errors or userUpdateForm.non_field_errors %}
            $('#editProfileModal').foundation('reveal', 'open');
        {% endif %}
        $(document).foundation('tab', 'reflow');
    </script>
{% endblock javascript %}

OrderingSystem/accounts/templates/accounts/orderdetail.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active">
        </li>
    </ul>


{% endblock nav_section %}
{% block context %}
    <fieldset class="columns small-6 small-centered ">
        <legend >Order Detail:</legend>


        <ul>
            <h>Dishes:</h>
            {% if dishlist %}
                {% for dish in dishlist %}
                    <li style="list-style-type: none;">

                        <a class="medium"
                           href="/{{ dish.r.id }}/dishlist#{{ dish.d.id }}">{{ dish.d.name }}</a>
                        <h class="right"> {{ dish.d.price }}{{ '$ ×' }}{{ dish.n }}</h>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>


        <ul>
            <h>Delivery Type:</h>
            <li style="list-style-type: none;">
                {% for key, value in deliverytype.items %}
                    {% if key == order.delivery_type %}
                        <p>{{ value }}</p>
                    {% endif %}
                {% endfor %}
            </li>
        </ul>



        <ul>
            <h>Payment Status:</h>
            <li style="list-style-type: none;">
                {% for key, value in paytype.items %}
                    {% if key == order.paid %}
                        <p>{{ value }}</p>
                    {% endif %}
                {% endfor %}
            </li>
        </ul>


        {% if order.location %}


            <ul>
                <h>Location:</h>
                <li style="list-style-type: none;">

                    {{ order.location }}

                </li>
            </ul>

        {% endif %}

        <ul>
            <h>Order Time:</h>
            <li style="list-style-type: none;">

                {{ order.time }}

            </li>
        </ul>

        <ul>
            <h>Total Price:</h>
            <li style="list-style-type: none;">

                {{ order.total_price }}

            </li>
        </ul>


        <ul>
            <h>Discount:</h>
            <li style="list-style-type: none;">

                {{ order.discount }}

            </li>
        </ul>
    </fieldset>


{% endblock context %}

OrderingSystem/accounts/templates/accounts/orders.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active">
            </li>
    </ul>

{% endblock nav_section %}
{% block context %}

            <fieldset class="columns small-6 small-centered ">
            <legend >Orders:</legend>
            <ul>
                {% for order in orders %}


                        <li style="list-style-type: none;">
                            <a class="center"
                               href="{% url 'accounts:orderdetail' order.id%}">{{ 'Order:' }} {{ order.id }}</a>
                        <a class="right" href="{% url 'Customer:resaurant_detail' order.restaurant.id%}">{{ order.restaurant.name }}</a>
                        </li>


                {% endfor %}

            </ul>

        </fieldset>


{% endblock context %}

OrderingSystem/accounts/templates/accounts/profile.html
{% extends "Customer/base.html" %}
{% load staticfiles %}

{% block page_style %}
{% endblock page_style %}

{% block nav_section %}

    <ul class="right">
        <li class="active">
            <a id="modalLink" data-reveal-id="editProfileModal" href="#" class="button round right"
               style="padding: 8px;">Edit</a></li>
    </ul>

{% endblock nav_section %}

{% block context %}
    <div class="row">
        <fieldset>
            <legend>Profile</legend>
            <div class="row" data-equalizer>
                <div class="columns medium-6">
                    <fieldset data-equalizer-watch>
                        <legend>Avatar</legend>
                        {% if request.user.image %}
                            <img src="{{ request.user.image.url }}" style="max-height: 200px;">
                        {% endif %}
                    </fieldset>
                </div>
                <div class="columns medium-6">
                    <fieldset data-equalizer-watch>
                        <legend>Detail</legend>
                        <div class="row">
                            First Name: {{ request.user.first_name }}
                        </div>
                        <div class="row">
                            Last Name: {{ request.user.last_name }}

                        </div>
                        <div class="row">
                            Email: {{ request.user.email }}

                        </div>
                        <div class="row">
                            Last login time: {{ request.user.last_login }}
                        </div>
                        <div class="row">
                            Phone Number: {{ request.user.phone }}
                        </div>
                    </fieldset>

                </div>
            </div>
            <div class="row">
                <ul class="text-center stack-for-small round button-group">
                    <li><a class="button success" href="{% url 'accounts:orderPage' %}">View More Orders</a>
                    </li>
                    {% if request.user.restaurant %}
                        <li><a class="button"
                               href="{% url 'business:RestaurantPage' %}">Manage {{ request.user.restaurant.name }}</a>
                        </li>
                    {% else %}
                        <li><a class="button success" href="{% url 'business:SignUpPage' %}">start a
                            restaurant?</a></li>
                    {% endif %}

                </ul>
            </div>
        </fieldset>
    </div>



    <div id="editProfileModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true"
         role="dialog">
        <form action="{% url 'accounts:profilePage' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if userUpdateForm.non_field_errors %}
                <span class="error">{{ userUpdateForm.non_field_errors }}</span>
            {% endif %}
            {% for field in userUpdateForm %}
                <label class="{{ field.help_text|yesno:"has-tip," }}{{ field.errors|yesno:" error," }}"
                        {% if field.help_text %}
                       data-tooltip aria-haspopup="true"
                       title="{{ field.help_text }}"{% endif %}>
                    {{ field.label }}
                    <small>{{ field.field.required|yesno:'required,' }}</small>
                    {{ field }}
                </label>
                {% if field.errors %}
                    <small class="error">{{ field.errors }}</small>
                {% endif %}
            {% endfor %}
            <input class="small button success right" type="submit" value="Submit"/>
        </form>
    </div>
{% endblock context %}

{% block javascript %}
    <script>
        {% if userUpdateForm.errors or userUpdateForm.non_field_errors %}
            $('#editProfileModal').foundation('reveal', 'open');
        {% endif %}
        $(document).foundation('tab', 'reflow');
    </script>
{% endblock javascript %}